# -*- coding: utf-8 -*-
"""Credit_Card_Fraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8V7NUUV-HNT8ZVk-WL23gT4F8bMQC41
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the credit card dataset
credit_card_data = pd.read_csv('/content/creditcard.csv')

# Initial inspection of data structure
print("--- Part 1: Initial Data Inspection ---")
print(credit_card_data.head(10))
print(credit_card_data.tail(10))
credit_card_data.info()
print("\nMissing values per column:")
print(credit_card_data.isnull().sum())

# Examine class imbalances and separate subsets
print("\nTarget Class Value Counts:")
print(credit_card_data['Class'].value_counts())

legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(f"Legitimate Transactions Shape: {legit.shape}")
print(f"Fraudulent Transactions Shape: {fraud.shape}")

print("\nLegitimate Amount Summary Statistics:")
print(legit.Amount.describe())
print("\nFraudulent Amount Summary Statistics:")
print(fraud.Amount.describe())

# 1. Visualizing the massive baseline class imbalance
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=credit_card_data, palette='Set2')
plt.title('Highly Imbalanced Dataset: Legit vs Fraudulent Transactions')
plt.xticks([0, 1], ['Legit (0)', 'Fraud (1)'])
plt.ylabel('Number of Transactions')
plt.show()

# 2. Compare transaction amounts using a shared x-axis distribution
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6), sharex=True)
fig.suptitle('Transaction Amount Distribution per Class')

sns.histplot(legit.Amount, bins=50, ax=ax1, color='g', kde=True)
ax1.set_title('Legit Transactions')
ax1.set_ylabel('Number of Transactions')

sns.histplot(fraud.Amount, bins=50, ax=ax2, color='r', kde=True)
ax2.set_title('Fraud Transactions')
ax2.set_xlabel('Amount ($)')
ax2.set_ylabel('Number of Transactions')

plt.xlim((0, 20000))
plt.yscale('log') # Logarithmic scale allows visibility of low count buckets
plt.tight_layout()
plt.show()

# Observe global feature averages per class
print("\nMean of features grouped by baseline Class:")
print(credit_card_data.groupby('Class').mean())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Undersample legitimate records to balance classes
legit_sample = legit.sample(n=492, random_state=2)
new_dataset = pd.concat([legit_sample, fraud], axis=0)

print("--- Part 2: Balanced Subsample Dataset ---")
print(new_dataset.head())
print(new_dataset.tail())
print("\nBalanced Class Distribution:")
print(new_dataset['Class'].value_counts())

# 3. Verify balanced class counts visually
plt.figure(figsize=(5, 3))
sns.countplot(x='Class', data=new_dataset, palette='Blues')
plt.title('Balanced Dataset (Undersampled Legit to Match Fraud)')
plt.xticks([0, 1], ['Legit (0)', 'Fraud (1)'])
plt.show()

# 4. Correlation Heatmap to identify feature impact shifts
plt.figure(figsize=(12, 10))
sns.heatmap(new_dataset.corr(), cmap='coolwarm', annot=False, fmt='.2f')
plt.title('Feature Correlation Matrix on Balanced Data')
plt.show()

print("\nMean of features grouped by balanced Class:")
print(new_dataset.groupby('Class').mean())

# Segmenting dependent and independent variables
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

# Stratified Splitting into Training and Test partitions
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
print(f"\nData Shapes -> Full: {X.shape} | Train: {X_train.shape} | Test: {X_test.shape}")

# Model Instantiation and Fitting
model = LogisticRegression(max_iter=1000)
model.fit(X_train, Y_train)

# Evaluation on Training Split
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print(f'\nAccuracy on Training data : {training_data_accuracy:.4f}')

# Evaluation on Testing Split
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(f'Accuracy score on Test Data : {test_data_accuracy:.4f}\n')

# 5. Plot the Confusion Matrix
cm = confusion_matrix(Y_test, X_test_prediction)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Predicted Legit', 'Predicted Fraud'],
            yticklabels=['Actual Legit', 'Actual Fraud'])
plt.title('Confusion Matrix: Logistic Regression Performance')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

# Display precision, recall, and f1 scores
print("\nClassification Report:\n")
print(classification_report(Y_test, X_test_prediction, target_names=['Legit', 'Fraud']))