# -*- coding: utf-8 -*-
"""Credit_Card_Fraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8V7NUUV-HNT8ZVk-WL23gT4F8bMQC41
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the credit card dataset
credit_card_data = pd.read_csv('/content/creditcard.csv')

# Initial inspection of data structure
print("--- Part 1: Initial Data Inspection ---")
print(credit_card_data.head(10))
print(credit_card_data.tail(10))
credit_card_data.info()
print("\nMissing values per column:")
print(credit_card_data.isnull().sum())

# Examine class imbalances and separate subsets
print("\nTarget Class Value Counts:")
print(credit_card_data['Class'].value_counts())

legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(f"Legitimate Transactions Shape: {legit.shape}")
print(f"Fraudulent Transactions Shape: {fraud.shape}")

print("\nLegitimate Amount Summary Statistics:")
print(legit.Amount.describe())
print("\nFraudulent Amount Summary Statistics:")
print(fraud.Amount.describe())

# 1. Visualizing the massive baseline class imbalance
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=credit_card_data, palette='Set2')
plt.title('Highly Imbalanced Dataset: Legit vs Fraudulent Transactions')
plt.xticks([0, 1], ['Legit (0)', 'Fraud (1)'])
plt.ylabel('Number of Transactions')
plt.show()

# 2. Compare transaction amounts using a shared x-axis distribution
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6), sharex=True)
fig.suptitle('Transaction Amount Distribution per Class')

sns.histplot(legit.Amount, bins=50, ax=ax1, color='g', kde=True)
ax1.set_title('Legit Transactions')
ax1.set_ylabel('Number of Transactions')

sns.histplot(fraud.Amount, bins=50, ax=ax2, color='r', kde=True)
ax2.set_title('Fraud Transactions')
ax2.set_xlabel('Amount ($)')
ax2.set_ylabel('Number of Transactions')

plt.xlim((0, 20000))
plt.yscale('log') # Logarithmic scale allows visibility of low count buckets
plt.tight_layout()
plt.show()

# Observe global feature averages per class
print("\nMean of features grouped by baseline Class:")
print(credit_card_data.groupby('Class').mean())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Undersample legitimate records to balance classes
legit_sample = legit.sample(n=492, random_state=2)
new_dataset = pd.concat([legit_sample, fraud], axis=0)

print("--- Part 2: Balanced Subsample Dataset ---")
print(new_dataset.head())
print(new_dataset.tail())
print("\nBalanced Class Distribution:")
print(new_dataset['Class'].value_counts())

# 3. Verify balanced class counts visually
plt.figure(figsize=(5, 3))
sns.countplot(x='Class', data=new_dataset, palette='Blues')
plt.title('Balanced Dataset (Undersampled Legit to Match Fraud)')
plt.xticks([0, 1], ['Legit (0)', 'Fraud (1)'])
plt.show()

# 4. Correlation Heatmap to identify feature impact shifts
plt.figure(figsize=(12, 10))
sns.heatmap(new_dataset.corr(), cmap='coolwarm', annot=False, fmt='.2f')
plt.title('Feature Correlation Matrix on Balanced Data')
plt.show()

print("\nMean of features grouped by balanced Class:")
print(new_dataset.groupby('Class').mean())

# Segmenting dependent and independent variables
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

# Stratified Splitting into Training and Test partitions
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
print(f"\nData Shapes -> Full: {X.shape} | Train: {X_train.shape} | Test: {X_test.shape}")

# Model Instantiation and Fitting
model = LogisticRegression(max_iter=1000)
model.fit(X_train, Y_train)

# Evaluation on Training Split
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print(f'\nAccuracy on Training data : {training_data_accuracy:.4f}')

# Evaluation on Testing Split
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(f'Accuracy score on Test Data : {test_data_accuracy:.4f}\n')

# 5. Plot the Confusion Matrix
cm = confusion_matrix(Y_test, X_test_prediction)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Predicted Legit', 'Predicted Fraud'],
            yticklabels=['Actual Legit', 'Actual Fraud'])
plt.title('Confusion Matrix: Logistic Regression Performance')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

# Display precision, recall, and f1 scores
print("\nClassification Report:\n")
print(classification_report(Y_test, X_test_prediction, target_names=['Legit', 'Fraud']))

import joblib
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

# =====================================================================
# DATA PREPARATION (Ensuring continuity with Part 2 variables)
# =====================================================================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
y_clf_train = Y_train
y_clf_test = Y_test

# =====================================================================
# TASK 1: Decision Tree baseline
# =====================================================================
dt_baseline = DecisionTreeClassifier(random_state=42)
dt_baseline.fit(X_train_scaled, y_clf_train)

dt_b_train_acc = accuracy_score(y_clf_train, dt_baseline.predict(X_train_scaled))
dt_b_test_acc = accuracy_score(y_clf_test, dt_baseline.predict(X_test_scaled))

print("--- Task 1: Decision Tree Baseline ---")
print(f"Training Accuracy: {dt_b_train_acc:.4f}")
print(f"Test Accuracy:     {dt_b_test_acc:.4f}\n")

# =====================================================================
# TASK 2: Controlled Decision Tree
# =====================================================================
dt_controlled = DecisionTreeClassifier(max_depth=5, min_samples_split=20, random_state=42)
dt_controlled.fit(X_train_scaled, y_clf_train)

dt_c_train_acc = accuracy_score(y_clf_train, dt_controlled.predict(X_train_scaled))
dt_c_test_acc = accuracy_score(y_clf_test, dt_controlled.predict(X_test_scaled))

print("--- Task 2: Controlled Decision Tree ---")
print(f"Training Accuracy: {dt_c_train_acc:.4f}")
print(f"Test Accuracy:     {dt_c_test_acc:.4f}\n")

# =====================================================================
# TASK 3: Gini vs Entropy comparison
# =====================================================================
dt_gini = DecisionTreeClassifier(max_depth=5, criterion='gini', random_state=42)
dt_entropy = DecisionTreeClassifier(max_depth=5, criterion='entropy', random_state=42)

dt_gini.fit(X_train_scaled, y_clf_train)
dt_entropy.fit(X_train_scaled, y_clf_train)

print("--- Task 3: Criterion Comparison (max_depth=5) ---")
print(f"Gini Test Accuracy:    {accuracy_score(y_clf_test, dt_gini.predict(X_test_scaled)):.4f}")
print(f"Entropy Test Accuracy: {accuracy_score(y_clf_test, dt_entropy.predict(X_test_scaled)):.4f}\n")

# =====================================================================
# TASK 4: Random Forest
# =====================================================================
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train_scaled, y_clf_train)

rf_train_acc = accuracy_score(y_clf_train, rf_model.predict(X_train_scaled))
rf_test_acc = accuracy_score(y_clf_test, rf_model.predict(X_test_scaled))
rf_test_auc = roc_auc_score(y_clf_test, rf_model.predict_proba(X_test_scaled)[:, 1])

print("--- Task 4: Random Forest ---")
print(f"Training Accuracy: {rf_train_acc:.4f}")
print(f"Test Accuracy:     {rf_test_acc:.4f}")
print(f"Test ROC-AUC:      {rf_test_auc:.4f}\n")

# Display top 5 features
importances = rf_model.feature_importances_
indices = np.argsort(importances)[::-1]
features = X.columns

print("Top 5 Features by Importance:")
for i in range(5):
    print(f"{i+1}. Feature '{features[indices[i]]}': {importances[indices[i]]:.4f}")
print()

# =====================================================================
# TASK 4a: Gradient Boosting
# =====================================================================
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb_model.fit(X_train_scaled, y_clf_train)

gb_train_acc = accuracy_score(y_clf_train, gb_model.predict(X_train_scaled))
gb_test_acc = accuracy_score(y_clf_test, gb_model.predict(X_test_scaled))
gb_test_auc = roc_auc_score(y_clf_test, gb_model.predict_proba(X_test_scaled)[:, 1])

print("--- Task 4a: Gradient Boosting ---")
print(f"Training Accuracy: {gb_train_acc:.4f}")
print(f"Test Accuracy:     {gb_test_acc:.4f}")
print(f"Test ROC-AUC:      {gb_test_auc:.4f}\n")

# =====================================================================
# TASK 4b: Feature ablation study
# =====================================================================
lowest_5_indices = indices[-5:]
lowest_5_features = [features[i] for i in lowest_5_indices]

X_train_reduced = pd.DataFrame(X_train_scaled, columns=features).drop(columns=lowest_5_features)
X_test_reduced = pd.DataFrame(X_test_scaled, columns=features).drop(columns=lowest_5_features)

rf_reduced = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_reduced.fit(X_train_reduced, y_clf_train)
rf_reduced_auc = roc_auc_score(y_clf_test, rf_reduced.predict_proba(X_test_reduced)[:, 1])

print("--- Task 4b: Feature Ablation Study ---")
print(f"Features Removed: {lowest_5_features}")
print(f"Full Model Test ROC-AUC:    {rf_test_auc:.4f}")
print(f"Reduced Model Test ROC-AUC: {rf_reduced_auc:.4f}\n")

# =====================================================================
# TASK 5: Cross-validated comparison
# =====================================================================
cv_strategy = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models_dict = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Controlled DT': DecisionTreeClassifier(max_depth=5, min_samples_split=20, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
}

print("--- Task 5: 5-Fold Cross-Validation (ROC-AUC) ---")
for name, model_instance in models_dict.items():
    scores = cross_val_score(model_instance, X_train_scaled, y_clf_train, cv=cv_strategy, scoring='roc_auc')
    print(f"{name:20} -> Mean AUC: {scores.mean():.4f} | Std AUC: {scores.std():.4f}")
print()

# =====================================================================
# TASK 6: Hyperparameter tuning with GridSearchCV
# =====================================================================
param_grid = {
    'randomforestclassifier__n_estimators': [50, 100, 200],
    'randomforestclassifier__max_depth': [5, 10, None],
    'randomforestclassifier__min_samples_leaf': [1, 5]
}

pipeline = make_pipeline(
    SimpleImputer(strategy='median'),
    StandardScaler(),
    RandomForestClassifier(random_state=42)
)

grid_search = GridSearchCV(pipeline, param_grid, cv=cv_strategy, scoring='roc_auc', n_jobs=-1)
grid_search.fit(X_train, y_clf_train)

best_pipeline = grid_search.best_estimator_
print("--- Task 6: Hyperparameter Tuning ---")
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best CV ROC-AUC:  {grid_search.best_score_:.4f}\n")

# =====================================================================
# TASK 7: Manual learning curve
# =====================================================================
fractions = [0.2, 0.4, 0.6, 0.8, 1.0]
lc_rows = []

for f in fractions:
    n_samples = int(f * len(X_train))
    X_train_sub = X_train.iloc[:n_samples]
    y_train_sub = y_clf_train.iloc[:n_samples]

    best_pipeline.fit(X_train_sub, y_train_sub)

    train_auc = roc_auc_score(y_train_sub, best_pipeline.predict_proba(X_train_sub)[:, 1])
    test_auc = roc_auc_score(y_clf_test, best_pipeline.predict_proba(X_test)[:, 1])

    lc_rows.append({'Training fraction': f, 'Training AUC': train_auc, 'Test AUC': test_auc})

lc_df = pd.DataFrame(lc_rows)
print("--- Task 7: Manual Learning Curve Table ---")
print(lc_df.to_markdown(index=False), "\n")

# =====================================================================
# TASK 8: Serialize the best model
# =====================================================================
joblib.dump(best_pipeline, 'best_model.pkl')

print("--- Task 8: Verification of Serialized Model ---")
loaded_pipeline = joblib.load('best_model.pkl')
mock_rows = X_test.iloc[:2]
predictions = loaded_pipeline.predict(mock_rows)
print(f"Reloaded pipeline execution completed. Sample predictions: {predictions}\n")