# -*- coding: utf-8 -*-
"""Credit_Card_Fraud_part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8V7NUUV-HNT8ZVk-WL23gT4F8bMQC41
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the credit card dataset
credit_card_data = pd.read_csv('/content/creditcard.csv')

# Initial inspection of data structure
print("--- Part 1: Initial Data Inspection ---")
print(credit_card_data.head(10))
print(credit_card_data.tail(10))
credit_card_data.info()
print("\nMissing values per column:")
print(credit_card_data.isnull().sum())

# Examine class imbalances and separate subsets
print("\nTarget Class Value Counts:")
print(credit_card_data['Class'].value_counts())

legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(f"Legitimate Transactions Shape: {legit.shape}")
print(f"Fraudulent Transactions Shape: {fraud.shape}")

print("\nLegitimate Amount Summary Statistics:")
print(legit.Amount.describe())
print("\nFraudulent Amount Summary Statistics:")
print(fraud.Amount.describe())

# 1. Visualizing the massive baseline class imbalance
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=credit_card_data, palette='Set2')
plt.title('Highly Imbalanced Dataset: Legit vs Fraudulent Transactions')
plt.xticks([0, 1], ['Legit (0)', 'Fraud (1)'])
plt.ylabel('Number of Transactions')
plt.show()

# 2. Compare transaction amounts using a shared x-axis distribution
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6), sharex=True)
fig.suptitle('Transaction Amount Distribution per Class')

sns.histplot(legit.Amount, bins=50, ax=ax1, color='g', kde=True)
ax1.set_title('Legit Transactions')
ax1.set_ylabel('Number of Transactions')

sns.histplot(fraud.Amount, bins=50, ax=ax2, color='r', kde=True)
ax2.set_title('Fraud Transactions')
ax2.set_xlabel('Amount ($)')
ax2.set_ylabel('Number of Transactions')

plt.xlim((0, 20000))
plt.yscale('log') # Logarithmic scale allows visibility of low count buckets
plt.tight_layout()
plt.show()

# Observe global feature averages per class
print("\nMean of features grouped by baseline Class:")
print(credit_card_data.groupby('Class').mean())